### ISSUE TITLE
Issue: Está derrubando o serviço após enviar dois post de mesmo email e type

### ISSUE THREAD

**Issue by arthurboeck** [SOS-Covid/sos-covid-backend#16]
End-Point: http://sos-covid-backend.herokuapp.com/user/register

Payload:
{
	"email": "fernando@hotmail.com",
	"password": "meupassforte",
	"cpf_cnpj": "028887663612",
	"phone1": "51 991517810",
	"type": "CONTRIBUTOR",
	"first_name": "Fernando",
	"last_name": "Da Silva"
}

**Comment by RunnableLian** [comment]
Arthur, eu vi esse bug e vou tratar ele já, assim que tiver corrigido atualizo aqui.

**Comment by RunnableLian** [comment]
@arthurboeck valida ai, o denner já tinha corrigido o tratamento de erro.

**Comment by arthurboeck** [comment]
Fechado!!!
