### ISSUE TITLE
Issue: validação dos atributos do Doador

### ISSUE THREAD

**Issue by arthurboeck** [SOS-Covid/sos-covid-backend#20]
- Add atributos de endereço (rua, número, complemente, cep, cidade, bairro, região (zona sul, zona norte) – não obrigatório
- Add atributo Status (ativo ou inativo)
- Add atributo Data do cadastro
- Add atributo Data último acesso

**Comment by RunnableLian** [comment]
@arthurboeck vou verificar, o de endereço pode enviar o address: { ... }, igual nos demais payloads que ele deve permitir o cadastro.
Vou inserir o status, data de cadastro e data do último acesso.

**Comment by arthurboeck** [comment]
Blzz... Soh tem que add a Rua no addres... pq nos outros nao tem.

**Comment by RunnableLian** [comment]
@arthurboeck ajustado, collections atualizadas tbm.
Rua é o atributo street dentro de address: {"street": "Rua dos açorianos"}

**Comment by RunnableLian** [comment]
@arthurboeck testa aee.

**Comment by arthurboeck** [comment]
@LianRolim faltou o status ativo

**Comment by RunnableLian** [comment]
pode enviar o "status: "ATIVO" que ele já grava.

**Comment by arthurboeck** [comment]
TOP!!!
