### ISSUE TITLE
Issue: validação dos atributos da Entidade

### ISSUE THREAD

**Issue by arthurboeck** [SOS-Covid/sos-covid-backend#21]
- Remover atributos de Dados Bancários (account_bank)
- Add atributo Quantidade de Cestas Basicas por Semana (meta desejada)
- Add atributo Data do Cadastro
- Add atributo Status (Ativo/Inativo)
- Add atributo Rua dentro do array address
- Add atributo Quem Ajuda

**Comment by RunnableLian** [comment]
@arthurboeck ajustando, já informo assim q corrigir

**Comment by RunnableLian** [comment]
ajustado
O account_bank é só remover do payload e não enviar.
quantidade de cestas básicas é o atributo "goal"
inserido o atributo registred_at para data de cadastro
inserido status como status mesmo.
adicionado o address como array, recebe vários endereços agora. 
* Importante * <-- Todos os payloads agora recebem um array de endereços, ajustei a collection pode olhar lá.
@arthurboeck

**Comment by arthurboeck** [comment]
@LianRolim faltou o atributo Quem Ajuda.
Ex.: asilos, creches, comunidade carente, etc

**Comment by RunnableLian** [comment]
é o assisted_entities

**Comment by RunnableLian** [comment]
"assisted_entities": [
        {
            "name": "Fernando da silva",
            "street": "Av. Brasil",
            "number": 123,
            "complement": "Sala 1",
            "district": "Centro",
            "city": "Porto Alegre",
            "state": "RS",
            "country": "Brasil",
            "postal_code": "90520000"
        },
        {
            "name": "João Manoel",
            "street": "Restinga",
            "number": 123,
            "complement": "Sala 1",
            "district": "Centro",
            "city": "Porto Alegre",
            "state": "RS",
            "country": "Brasil",
            "postal_code": "90520000"
        }
    ]

**Comment by RunnableLian** [comment]
dentro do assisted_entities pode enviar qualquer coisa que o front precisar se precisar mudar os atributos de dentro.

**Comment by arthurboeck** [comment]
Feito!
