### ISSUE TITLE
Issue: validação dos atributos do Mercado

### ISSUE THREAD

**Issue by arthurboeck** [SOS-Covid/sos-covid-backend#23]
- Add atibuto Nome Fantasia
- Ter atributos separados para CNPJ do  Estabelecimento, e CPF do Responsavel
- Add atributo Celular
- Add atributo Data Cadastro
- Add atributo Status (ativo/inativo)

**Comment by RunnableLian** [comment]
nome fantasia é o atributo "name_market"
razão social é o atributo "social_reason"
atributo celular tem o phone1 e o phone2 para gravar estes campos.
data do cadastro é o atributo registred_at
status é o atributo status mesmo
cpf do responsável o atributo "cpf_responsible"

**Comment by arthurboeck** [comment]
Feito!
