### ISSUE TITLE
Issue: 404 ao chamar o end-point password-recovery com um email valido

### ISSUE THREAD

**Issue by arthurboeck** [SOS-Covid/sos-covid-backend#25]
ao dar um get na seguinte rota: 
http://sos-covid-backend.herokuapp.com/password-recovery/arthurguterres@outlook.com

Eh retornado um 404, porém o email existe na base.

![image](https://user-images.githubusercontent.com/10471827/77836925-9c71ce00-7139-11ea-9123-6da6073801e0.png)

**Comment by dennerevaldt** [comment]
http://sos-covid-backend.herokuapp.com**/user/**password-recovery/arthurguterres@outlook.com faltou ali @arthurboeck, testei e aqui e foi

**Comment by arthurboeck** [comment]
Eitaaa... cagada minhaa... hahah
