### ISSUE TITLE
Post Create ONG - Parâmetro Password

### ISSUE THREAD

**Issue by gmirandars** [SOS-Covid/sos-covid-backend#31]
1. Quando realizada uma chamada na rota de criação de ONG, e informo um password vazio acredito que deveríamos validar se o valor passado no payload é não nulo. No caso consegui cadastrar uma ONG com password com o valor "". 

Payload: 

{
	"email": "lianrolim999@gmail.com",
	"password": "",
	"first_name": "sou",
	"last_name": "o responsavel",
	"name_organization": "Mensageiros da caridade",
	"cpf_cnpj": "028887663612",
	"phone1": "51 991517810",
	"type": "ORGANIZATION",
	"site": "https://mensageirosdacaridade.com",
	"facebook": "instagram.com/mensageiros",
	"instagram": "facebook.com/mensageiros",
	"group_finality": "Ação social",
	"accepted_donate": true,
	"address": {
		"street": "Av. Brasil",
		"number": 123,
		"complement": "Sala 1",
		"district": "Centro",
		"city": "Porto Alegre",
		"state": "RS",
		"country": "Brasil",
		"postal_code": "90520000"
	},
	"account_bank": {
		"name_banking": "ITAU",
		"agency": "0434",
		"account_number": "559141",
		"name_favored": "Ong Mensageiros",
		"cpf_cnpj": "028887663612"
	},
	"help_types": [
		"Transferência bancária",
		"Doação direta de alimentos",
		"Doação de roupas"
	], 
	"served_region": [
		"Zona Sul",
		"Zona Norte",
		"Restinga"
	]
}

**Comment by RunnableLian** [comment]
Tá sem nada de validação nesses payload ainda, pq vai ter uma cacetada de coisa pra validar. Acho que nesse primeiro MVP 0, vamos seguir no cenário feliz e tentar bloquear no front o que é obrigatório ou não, e após a gente revisita e coloca essas validações no backend tbm pra não deixar mt livre.

**Comment by gmirandars** [comment]
Beleza
