### ISSUE TITLE
Post Create ONG - Parâmetro Type

### ISSUE THREAD

**Issue by gmirandars** [SOS-Covid/sos-covid-backend#33]
1. Acredito que seria melhor criar uma classe de constante/enum para tipar os valores aceitos para este campo para que somente sejam aceitos valores validos quando realizada uma chamada na rota. 
 Atualmente como aceitamos qualquer string e o tipo é um valor chave para a aplicação acredito que seja importe definir os valores que iremos aceitar do front. 

2. Type esta definido para o tipo String porém esta aceitando number no payload. 

Payload:

{
	"email": "teste5@gmail.com",
	"password": "meupassforte",
	"first_name": "sou",
	"last_name": "o responsavel",
	"name_organization": "Mensageiros da caridade",
	"cpf_cnpj": "028887663612",
	"phone1": "51 991517810",
	"type": 123,
	"site": "https://mensageirosdacaridade.com",
	"facebook": "instagram.com/mensageiros",
	"instagram": "facebook.com/mensageiros",
	"group_finality": "Ação social",
	"accepted_donate": true,
	"address": {
		"street": "Av. Brasil",
		"number": 123,
		"complement": "Sala 1",
		"district": "Centro",
		"city": "Porto Alegre",
		"state": "RS",
		"country": "Brasil",
		"postal_code": "90520000"
	},
	"account_bank": {
		"name_banking": "ITAU",
		"agency": "0434",
		"account_number": "559141",
		"name_favored": "Ong Mensageiros",
		"cpf_cnpj": "028887663612"
	},
	"help_types": [
		"Transferência bancária",
		"Doação direta de alimentos",
		"Doação de roupas"
	], 
	"served_region": [
		"Zona Sul",
		"Zona Norte",
		"Restinga"
	]
}

**Comment by RunnableLian** [comment]
Corrigido pelo denner, @gmirandars testa ae.
