### ISSUE TITLE
Issue: Está retornando 404 ao Ativar um usuário.

### ISSUE THREAD

**Issue by arthurboeck** [SOS-Covid/sos-covid-backend#36]
Ao ativar um usuário está retornando um 404, trocar por um 200.

End-Point: http://sos-covid-backend.herokuapp.com/user/active/

**Comment by dennerevaldt** [comment]
@arthurboeck  só retorna 404 se o usuário passado não existir, esse é o link que vai para o e-mail cadastrado. Por exemplo: **http://sos-covid-backend.herokuapp.com/user/active/arthur@email.com**. Isso vai estar dentro do e-mail enviado para ativar.

**Comment by arthurboeck** [comment]
Simm... Neste caso OK.

Porém mesmo existindo, ele retornar um 404.
Inclusive, olhei no fonte, e vi esse cara retornando lah, nao sei se nao eh esse o problema:
        res.sendStatus(HttpStatus.NO_CONTENT);


![image](https://user-images.githubusercontent.com/10471827/77851850-a59e8180-71b1-11ea-9303-77ac72918b6c.png)

**Comment by dennerevaldt** [comment]
Ahh, entendi. É que o seguinte, essa rota redireciona para uma url do frontend. O fluxo é o seguinte:

**RECUPERAR SENHA:**

-> Pede pra recuperar e recebe no email (**/recovery**);
-> Clica no link do email, ele bate no backend e valida o link com código e redireciona para uma url do frontend com uma chave nessa url;
-> Front apresenta tela para a nova senha, pega o valor da nova senha do usuário e nos envia para rota de patch (**/password**)  com a chave via header junto;

**ATIVAR USUÁRIO:**

-> Clica no link por e-mail, valida e ativa no backend e ja redireciona o usuário para "home" do site;

Para testar o que estou te falando, cria um registro de usuário novo e ao invés do postman, cola a URL de ativação no browser que tu vai visualizar o que estou dizendo. Esse 404 no postman é porque não existe a URL redirecionada ainda pro front, no browser ele mostra isso.

**Comment by arthurboeck** [comment]
Tahhh... Saqueiiii...
Agora entendi
