### ISSUE TITLE
Issue: Create Campanha

### ISSUE THREAD

**Issue by arthurboeck** [SOS-Covid/sos-covid-backend#50]
nao está validando se o reference_user está em formato de endereço valido, e nem mesmo, se o mesmo existe

**Comment by RunnableLian** [comment]
@arthurboeck, não está mesmo. Vou ajustar.

**Comment by RunnableLian** [comment]
@arthurboeck  ajustado, testa ae;

**Comment by arthurboeck** [comment]
TOPPP!!!
