### ISSUE TITLE
Issue: não está permitindo criar mais de uma campanha por usuário

### ISSUE THREAD

**Issue by arthurboeck** [SOS-Covid/sos-covid-backend#56]
Ao criar duas campanhas para o mesmo email, está retornando um erro 500.

{
    "error": "E11000 duplicate key error index: heroku_3qqf9tl4.campaigns.$reference_user_1 dup key: { : \"teste844792644@teste.com\" }"
}

**Comment by arthurboeck** [comment]
@LianRolim

**Comment by arthurboeck** [comment]
O erro continua...

**Comment by RunnableLian** [comment]
Acabei de subir local e testar apontando pro meu mlab, criei umas 10 campanhas para o mesmo email.

**Comment by RunnableLian** [comment]
@arthurboeck  tem alguma coisa estranha ae.

**Comment by arthurboeck** [comment]
Corrigido.. Era problema no Heroku
